language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog
# cache this directory
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - git config --global user.name "erbiduo"
  - git config --global user.email "wyt157461501@gmail.com"
  - openssl aes-256-cbc -K $encrypted_aff2c0aff581_key -iv $encrypted_aff2c0aff581_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
  - export HEXO_DEPLOYER_REPO=https://$REPO_TOKEN@github.com/erbiduo/Myblog.git
  - git clone https://github.com/erbiduo/hexo-casper.git themes/hexo-casper
install:
  - npm install # 安装 package.json 中的插件
  - npm install gulp
# script:
#   - hexo clean
#   - hexo generate
after_success:
  - git config --global user.name "erbiduo"
  - git config --global user.email "wyt157461501@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - npm run update