language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog
# cache this directory
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - git config --global user.name "erbiduo"
  - git config --global user.email "wyt157461501@gmail.com"
  - openssl aes-256-cbc -K $encrypted_aff2c0aff581_key -iv $encrypted_aff2c0aff581_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
#  - git clone -b git@github.com:erbiduo/sagiri_1.git themes/sagiri_1
install:
  - npm install # 安装 package.json 中的插件
script:
  - hexo clean
  - hexo generate
after_success:
  - git config --global user.name "erbiduo"
  - git config --global user.email "wyt157461501@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy